### ISSUE TITLE
resetがきかない

### ISSUE THREAD

**Issue by vestige** [mame-n/toteka04_timer#6]
:boom:

```
/home/pi/spike/mame_timer/mcpi_ruby.rb:60:in `load_world': uninitialized constant NumericalMCPI::PStore (NameError)
    from /home/pi/spike/mame_timer/timermain.rb:58:in `reset_timer'
    from cui.rb:40:in `<main>'
```

**Comment by mame-n** [comment]
!!!
安心してください。知ってました。。。。

**Comment by vestige** [comment]
確認しました。
